/* Generated By:JJTree&JavaCC: Do not edit this line. LuceneParserTokenManager.java */
package com.sun.labs.minion.retrieval.parser;

public class LuceneParserTokenManager implements LuceneParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x20000000L) != 0L)
            return 52;
         if ((active0 & 0x200000000L) != 0L)
            return 53;
         if ((active0 & 0xc080000000L) != 0L)
            return 54;
         if ((active0 & 0x800018000000L) != 0L)
         {
            jjmatchedKind = 48;
            return 55;
         }
         if ((active0 & 0x40000000L) != 0L)
            return 56;
         if ((active0 & 0x10000000000L) != 0L)
            return 12;
         if ((active0 & 0x100000000L) != 0L)
            return 57;
         return -1;
      case 1:
         if ((active0 & 0x8000000L) != 0L)
            return 55;
         if ((active0 & 0x800010000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
            return 55;
         }
         return -1;
      case 2:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 2;
            return 55;
         }
         if ((active0 & 0x10000000L) != 0L)
            return 55;
         return -1;
      case 3:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 3;
            return 55;
         }
         return -1;
      case 4:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 4;
            return 54;
         }
         return -1;
      case 5:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 5;
            return 54;
         }
         return -1;
      case 6:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 6;
            return 54;
         }
         return -1;
      case 7:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 7;
            return 54;
         }
         return -1;
      case 8:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 8;
            return 54;
         }
         return -1;
      case 9:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 9;
            return 54;
         }
         return -1;
      case 10:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 10;
            return 54;
         }
         return -1;
      case 11:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 11;
            return 54;
         }
         return -1;
      case 12:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 12;
            return 54;
         }
         return -1;
      case 13:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 13;
            return 54;
         }
         return -1;
      case 14:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 14;
            return 54;
         }
         return -1;
      case 15:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 15;
            return 54;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 33, 53);
      case 40:
         return jjStartNfaWithStates_0(0, 38, 54);
      case 41:
         return jjStartNfaWithStates_0(0, 39, 54);
      case 43:
         return jjStartNfaWithStates_0(0, 29, 52);
      case 45:
         return jjStartNfaWithStates_0(0, 30, 56);
      case 47:
         return jjStartNfaWithStates_0(0, 31, 54);
      case 58:
         return jjStopAtPos(0, 41);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 91:
         return jjStopAtPos(0, 34);
      case 93:
         return jjStopAtPos(0, 35);
      case 94:
         return jjStartNfaWithStates_0(0, 40, 12);
      case 123:
         return jjStopAtPos(0, 36);
      case 125:
         return jjStopAtPos(0, 37);
      case 126:
         return jjStartNfaWithStates_0(0, 32, 57);
      case 160:
         return jjStopAtPos(0, 2);
      case 5760:
         return jjStopAtPos(0, 3);
      case 6158:
         return jjStopAtPos(0, 4);
      case 8192:
         return jjStopAtPos(0, 5);
      case 8193:
         return jjStopAtPos(0, 6);
      case 8194:
         return jjStopAtPos(0, 7);
      case 8195:
         return jjStopAtPos(0, 8);
      case 8196:
         return jjStopAtPos(0, 9);
      case 8197:
         return jjStopAtPos(0, 10);
      case 8198:
         return jjStopAtPos(0, 11);
      case 8199:
         return jjStopAtPos(0, 12);
      case 8200:
         return jjStopAtPos(0, 13);
      case 8201:
         return jjStopAtPos(0, 14);
      case 8202:
         return jjStopAtPos(0, 15);
      case 8203:
         return jjStopAtPos(0, 16);
      case 8232:
         return jjStopAtPos(0, 17);
      case 8233:
         return jjStopAtPos(0, 18);
      case 8239:
         return jjStopAtPos(0, 19);
      case 8287:
         return jjStopAtPos(0, 20);
      case 12288:
         return jjStopAtPos(0, 21);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L);
      case 79:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 27, 55);
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 84:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 28, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private final int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private final int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 70:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private final int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa14_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private final int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa15_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private final int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa16_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private final int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(16, 47, 54);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffe000000025040L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x3600000000ffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec3 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec4 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L
};
static final long[] jjbitVec5 = {
   0x0L, 0x0L, 0xffffffff00000000L, 0xffffffffffffffffL
};
static final long[] jjbitVec6 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec7 = {
   0x0L, 0xffffffffffff0000L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec8 = {
   0xffffffffffffffffL, 0xffff00000000ffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec9 = {
   0x0L, 0xffffffff00000000L, 0xffffffffffffffffL, 0xffffffffL
};
static final long[] jjbitVec10 = {
   0x200002L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec11 = {
   0x0L, 0x0L, 0x420040000000000L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec12 = {
   0x7fffffffffffffL, 0xffffffffffff0000L, 0xffffffffffffffffL, 0x401f0003ffc3L
};
static final long[] jjbitVec13 = {
   0x0L, 0x400000000000000L, 0xfffffffbffffd740L, 0xfbfffffffff7fffL
};
static final long[] jjbitVec14 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffffffc03L, 0x33fffffffff7fffL
};
static final long[] jjbitVec15 = {
   0xfffe00000000ffffL, 0xfffffffe027fffffL, 0xffL, 0x707ffffff0000L
};
static final long[] jjbitVec16 = {
   0xfffffffd0000L, 0xe000L, 0x2003fffffffffL, 0x0L
};
static final long[] jjbitVec17 = {
   0x23fffffffffffff0L, 0xffc3ff010000L, 0x23c5fdfffff99fe0L, 0x3ffc3b0000000L
};
static final long[] jjbitVec18 = {
   0x36dfdfffff987e0L, 0x1cffc05e000000L, 0x23edfdfffffbbfe0L, 0xffc300010000L
};
static final long[] jjbitVec19 = {
   0x23edfdfffff99fe0L, 0x2ffc3b0000000L, 0x0L, 0x0L
};
static final long[] jjbitVec20 = {
   0x0L, 0x0L, 0x2ffbfffffc7fffe0L, 0x7fL
};
static final long[] jjbitVec21 = {
   0x6fbffffffffL, 0x3f03ffL, 0x0L, 0x0L
};
static final long[] jjbitVec22 = {
   0xffffffffffffff7fL, 0xffffffff3d7f3d7fL, 0x7f3d7fffffff3d7fL, 0xffff7fffff7f7f3dL
};
static final long[] jjbitVec23 = {
   0xffffffff7f3d7fffL, 0x3fe0007ffff7fL, 0xffffffff00000000L, 0x1fffffffffffffL
};
static final long[] jjbitVec24 = {
   0xffffffffffffffffL, 0x7f9fffffffffffL, 0xffffffff07fffffeL, 0x7ffffffffffL
};
static final long[] jjbitVec25 = {
   0x3ffff0003dfffL, 0x1dfff0003ffffL, 0xfffffffffffffL, 0x3ff10800000L
};
static final long[] jjbitVec26 = {
   0xffffffff03ff0000L, 0xffffffffffffffL, 0x1ffffffffffL, 0x0L
};
static final long[] jjbitVec27 = {
   0x1fffffffL, 0x1f3fffffffffc0L, 0x0L, 0x0L
};
static final long[] jjbitVec28 = {
   0xffffffffffffffffL, 0xfffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec29 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffff0fffffffL, 0x3ffffffffffffffL
};
static final long[] jjbitVec30 = {
   0xffffffff3f3fffffL, 0x3fffffffaaff3f3fL, 0x5fdfffffffffffffL, 0x1fdc1fff0fcf1fdcL
};
static final long[] jjbitVec31 = {
   0x0L, 0x8002000000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec32 = {
   0xe3fbbd503e2ffc84L, 0x3e0L, 0x0L, 0x0L
};
static final long[] jjbitVec33 = {
   0x5f7ffdffa0f8007fL, 0xffdbL, 0x0L, 0x0L
};
static final long[] jjbitVec34 = {
   0x7fffffe03ff0000L, 0x7fffffeL, 0x0L, 0x0L
};
static final long[] jjbitVec35 = {
   0x0L, 0x0L, 0x100000000L, 0x0L
};
static final long[] jjbitVec36 = {
   0x0L, 0x0L, 0x1L, 0x0L
};
static final long[] jjbitVec37 = {
   0x4000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec38 = {
   0x830000000fffL, 0x80000000L, 0x0L, 0x0L
};
static final long[] jjbitVec39 = {
   0x1L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec40 = {
   0x0L, 0x0L, 0x8880080200000000L, 0x0L
};
static final long[] jjbitVec41 = {
   0x0L, 0x4000000000000000L, 0x80L, 0x0L
};
static final long[] jjbitVec42 = {
   0x0L, 0xfc000000L, 0x4000000000000600L, 0x18000000000009L
};
static final long[] jjbitVec43 = {
   0x88003000L, 0x3c0000000000L, 0x0L, 0x100000L
};
static final long[] jjbitVec44 = {
   0x3fffL, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec45 = {
   0x0L, 0x1003000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec46 = {
   0x0L, 0x0L, 0x0L, 0x10000000000000L
};
static final long[] jjbitVec47 = {
   0x0L, 0xc008000L, 0x0L, 0x0L
};
static final long[] jjbitVec48 = {
   0x3c0000000007fff0L, 0x0L, 0x20L, 0x0L
};
static final long[] jjbitVec49 = {
   0x0L, 0xfc00L, 0x0L, 0x800000000000000L
};
static final long[] jjbitVec50 = {
   0x0L, 0x1fe00000000L, 0x0L, 0x0L
};
static final long[] jjbitVec51 = {
   0x0L, 0x600000000000L, 0x18000000L, 0x380000000000L
};
static final long[] jjbitVec52 = {
   0x60000000000000L, 0x0L, 0x0L, 0x7700000L
};
static final long[] jjbitVec53 = {
   0x7ffL, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec54 = {
   0x0L, 0x30L, 0x0L, 0x0L
};
static final long[] jjbitVec55 = {
   0xffff00ffffff0000L, 0x60000000009bffefL, 0x6000L, 0x0L
};
static final long[] jjbitVec56 = {
   0x60000000000L, 0x0L, 0x70000000000000L, 0x0L
};
static final long[] jjbitVec57 = {
   0x0L, 0x3fff0000000000L, 0x0L, 0xfc000000000L
};
static final long[] jjbitVec58 = {
   0x0L, 0x0L, 0x1fffff8L, 0x300000000f000000L
};
static final long[] jjbitVec59 = {
   0x20010000fff3ff0eL, 0x0L, 0x100000000L, 0x800000000000000L
};
static final long[] jjbitVec60 = {
   0xc000000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec61 = {
   0xffff000000000000L, 0xd0bfff7ffffL, 0x0L, 0x0L
};
static final long[] jjbitVec62 = {
   0xb80000018c00f7eeL, 0x3fa8000000L, 0x0L, 0x0L
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 52;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 54:
                  if ((0xd800f7fa00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 52:
                  if ((0xd800f7fa00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 8);
                  break;
               case 2:
                  if ((0xd800f7fa00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     jjCheckNAddStates(9, 14);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 8);
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 53:
                  if ((0xdc00fffb00000000L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  else if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 56:
                  if ((0xd800f7fa00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 8);
                  break;
               case 55:
                  if ((0xd800f7fa00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(48);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(24, 26);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(11);
                  break;
               case 57:
                  if ((0xd800f7fa00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAdd(33);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(32);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 3:
                  if (curChar == 38 && kind > 25)
                     kind = 25;
                  break;
               case 4:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 10:
                  if (curChar == 46)
                     jjCheckNAdd(11);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(11);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(13, 10);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(14);
                  break;
               case 15:
                  if (curChar == 34)
                     jjCheckNAddStates(5, 8);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 18:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 19:
                  if ((0xdc00fffb00000000L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 20:
                  if (curChar != 34)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddTwoStates(21, 23);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddTwoStates(22, 23);
                  break;
               case 24:
                  if (curChar == 46)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(25);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddStates(27, 29);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(27, 24);
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(28);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 31:
                  if (curChar == 46)
                     jjCheckNAdd(32);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(32);
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(33);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAddStates(9, 14);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(0, 4);
                  break;
               case 37:
                  if ((0xd800f7fa00000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(0, 4);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(30, 31);
                  break;
               case 40:
                  if (curChar == 46)
                     jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddTwoStates(41, 42);
                  break;
               case 43:
                  if (curChar == 46)
                     jjCheckNAdd(44);
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(44);
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(32, 34);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(46, 43);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(47);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(48);
                  break;
               case 49:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 54:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x5000000190000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 94)
                     jjAddStates(35, 36);
                  if (curChar == 126)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(37, 39);
                  }
                  break;
               case 52:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x5000000190000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     jjCheckNAddStates(9, 14);
                  }
                  else if ((0x5000000190000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 94)
                     jjAddStates(40, 41);
                  if (curChar == 126)
                  {
                     if (kind > 44)
                        kind = 44;
                     jjAddStates(42, 44);
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 5;
                  else if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 53:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  else if ((0x78000001f8000001L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 56:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x5000000190000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 94)
                     jjAddStates(35, 36);
                  if (curChar == 126)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(37, 39);
                  }
                  break;
               case 55:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(48);
                  }
                  else if ((0x5000000190000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 94)
                     jjAddStates(35, 36);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 126)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(37, 39);
                  }
                  break;
               case 57:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x5000000190000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 94)
                     jjAddStates(35, 36);
                  if (curChar == 126)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(37, 39);
                  }
                  break;
               case 0:
                  if (curChar == 68 && kind > 25)
                     kind = 25;
                  break;
               case 1:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 5:
                  if (curChar == 82 && kind > 26)
                     kind = 26;
                  break;
               case 6:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 124 && kind > 26)
                     kind = 26;
                  break;
               case 8:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 94)
                     jjAddStates(40, 41);
                  break;
               case 17:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 19:
                  if ((0x78000001f8000001L & l) != 0L)
                     jjCheckNAddStates(19, 23);
                  break;
               case 21:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 23:
                  if (curChar == 94)
                     jjAddStates(45, 46);
                  break;
               case 29:
                  if (curChar != 126)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjAddStates(42, 44);
                  break;
               case 34:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAddStates(9, 14);
                  break;
               case 36:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(0, 4);
                  break;
               case 37:
                  if ((0x5000000190000001L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(0, 4);
                  break;
               case 38:
                  if (curChar != 126)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(37, 39);
                  break;
               case 42:
                  if (curChar == 94)
                     jjAddStates(35, 36);
                  break;
               case 48:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(48);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 54:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(47, 51);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 52:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(47, 51);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 2:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 48)
                        kind = 48;
                     jjCheckNAddStates(9, 14);
                  }
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(52, 57);
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 53:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(58, 62);
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 23);
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 23);
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 23);
                  break;
               case 56:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(47, 51);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 55:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(47, 51);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAdd(48);
                  }
                  break;
               case 57:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(47, 51);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAddStates(0, 4);
                  }
                  break;
               case 16:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(58, 62);
                  break;
               case 17:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 23);
                  break;
               case 18:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 23);
                  break;
               case 19:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 23);
                  break;
               case 34:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjCheckNAddStates(9, 14);
                  break;
               case 35:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(47, 51);
                  break;
               case 36:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(0, 4);
                  break;
               case 37:
                  if (!jjCanMove_3(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(0, 4);
                  break;
               case 48:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(48);
                  break;
               case 50:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddStates(52, 57);
                  break;
               case 51:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(51);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 52 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   35, 36, 37, 38, 42, 16, 17, 18, 19, 35, 36, 37, 38, 42, 48, 15, 
   35, 36, 37, 16, 17, 18, 19, 20, 13, 10, 14, 27, 24, 28, 39, 40, 
   46, 43, 47, 43, 45, 39, 40, 42, 10, 12, 30, 31, 33, 24, 26, 36, 
   37, 38, 42, 35, 36, 37, 38, 42, 51, 35, 17, 18, 19, 20, 16, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 11:
         return ((jjbitVec2[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec3[i2] & l2) != 0L);
      case 15:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec8[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec9[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec11[i2] & l2) != 0L);
      case 2:
         return ((jjbitVec12[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec13[i2] & l2) != 0L);
      case 4:
         return ((jjbitVec14[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec15[i2] & l2) != 0L);
      case 7:
         return ((jjbitVec16[i2] & l2) != 0L);
      case 9:
         return ((jjbitVec17[i2] & l2) != 0L);
      case 10:
         return ((jjbitVec18[i2] & l2) != 0L);
      case 11:
         return ((jjbitVec19[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec20[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec21[i2] & l2) != 0L);
      case 18:
         return ((jjbitVec22[i2] & l2) != 0L);
      case 19:
         return ((jjbitVec23[i2] & l2) != 0L);
      case 20:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec24[i2] & l2) != 0L);
      case 23:
         return ((jjbitVec25[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec26[i2] & l2) != 0L);
      case 25:
         return ((jjbitVec27[i2] & l2) != 0L);
      case 29:
         return ((jjbitVec28[i2] & l2) != 0L);
      case 30:
         return ((jjbitVec29[i2] & l2) != 0L);
      case 31:
         return ((jjbitVec30[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec31[i2] & l2) != 0L);
      case 33:
         return ((jjbitVec32[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec33[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec34[i2] & l2) != 0L);
      default : 
         if ((jjbitVec10[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec35[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec36[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec37[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec38[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec39[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec40[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec41[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec42[i2] & l2) != 0L);
      case 6:
         return ((jjbitVec43[i2] & l2) != 0L);
      case 7:
         return ((jjbitVec44[i2] & l2) != 0L);
      case 9:
         return ((jjbitVec45[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec46[i2] & l2) != 0L);
      case 14:
         return ((jjbitVec47[i2] & l2) != 0L);
      case 15:
         return ((jjbitVec48[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec49[i2] & l2) != 0L);
      case 19:
         return ((jjbitVec50[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec51[i2] & l2) != 0L);
      case 23:
         return ((jjbitVec52[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec53[i2] & l2) != 0L);
      case 25:
         return ((jjbitVec54[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec55[i2] & l2) != 0L);
      case 35:
         return ((jjbitVec56[i2] & l2) != 0L);
      case 39:
         return ((jjbitVec57[i2] & l2) != 0L);
      case 41:
         return ((jjbitVec58[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec59[i2] & l2) != 0L);
      case 253:
         return ((jjbitVec60[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec61[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec62[i2] & l2) != 0L);
      default : 
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\124\117", "\116\117\124", "\53", "\55", "\57", "\176", "\42", "\133", "\135", "\173", 
"\175", "\50", "\51", "\136", "\72", null, null, null, null, null, 
"\120\101\116\104\55\111\123\55\125\116\104\105\106\111\116\105\104", null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x67f3fffe000001L, 0x5L, 
};
static final long[] jjtoSkip = {
   0x1fffffeL, 0x0L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[52];
private final int[] jjstateSet = new int[104];
protected char curChar;
public LuceneParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public LuceneParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 52; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
