/* Generated By:JJTree: Do not edit this line. LuceneASTdoParse.java */

package com.sun.labs.minion.retrieval.parser;

public class LuceneASTdoParse extends SimpleNode {
  public LuceneASTdoParse(int id) {
    super(id);
  }

  public LuceneASTdoParse(LuceneParser p, int id) {
    super(p, id);
  }

}
