/* Generated By:JJTree: Do not edit this line. LuceneASTterm.java */

package com.sun.labs.minion.retrieval.parser;

public class LuceneASTterm extends SimpleNode {
  public LuceneASTterm(int id) {
    super(id);
  }

  public LuceneASTterm(LuceneParser p, int id) {
    super(p, id);
  }

}
