/* Generated By:JJTree&JavaCC: Do not edit this line. LuceneParserConstants.java */
package com.sun.labs.minion.retrieval.parser;

public interface LuceneParserConstants {

  int EOF = 0;
  int AND = 25;
  int OR = 26;
  int TO = 27;
  int NOT = 28;
  int PLUS = 29;
  int MINUS = 30;
  int FSLASH = 31;
  int TILDE = 32;
  int DUBQUOTE = 33;
  int LB = 34;
  int RB = 35;
  int LC = 36;
  int RC = 37;
  int LP = 38;
  int RP = 39;
  int CAROT = 40;
  int COLON = 41;
  int INTEGER = 42;
  int DECIMAL = 43;
  int FUZZY = 44;
  int PROX = 45;
  int BOOST = 46;
  int PAND = 47;
  int VALIDCHAR = 48;
  int PHRASE = 49;
  int TERM = 50;
  int WHITESPACE = 51;
  int WHITECHAR = 52;
  int SPACESEPTOKEN = 53;
  int SPACESEPCHAR = 54;
  int SPACESEPCHAR1 = 55;
  int SPACESEPCHAR2 = 56;
  int SPACESEPCHAR3 = 57;
  int SPACESEPCHAR4 = 58;
  int SPACESEPCHAR5 = 59;
  int SPACESEPCHAR6 = 60;
  int SPACESEPCHAR7 = 61;
  int SPACESEPCHAR8 = 62;
  int SPACESEPCHAR9 = 63;
  int NGRAMTOKEN = 64;
  int NONSPACESEPCHAR = 65;
  int PUNCTUATION = 66;
  int PUNCTCHAR1 = 67;
  int PUNCTCHAR2 = 68;
  int SPECIAL = 69;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\u1680\"",
    "\"\\u180e\"",
    "\"\\u2000\"",
    "\"\\u2001\"",
    "\"\\u2002\"",
    "\"\\u2003\"",
    "\"\\u2004\"",
    "\"\\u2005\"",
    "\"\\u2006\"",
    "\"\\u2007\"",
    "\"\\u2008\"",
    "\"\\u2009\"",
    "\"\\u200a\"",
    "\"\\u200b\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "\"\\u202f\"",
    "\"\\u205f\"",
    "\"\\u3000\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<AND>",
    "<OR>",
    "\"TO\"",
    "\"NOT\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"~\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
    "\":\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<FUZZY>",
    "<PROX>",
    "<BOOST>",
    "\"PAND-IS-UNDEFINED\"",
    "<VALIDCHAR>",
    "<PHRASE>",
    "<TERM>",
    "<WHITESPACE>",
    "<WHITECHAR>",
    "<SPACESEPTOKEN>",
    "<SPACESEPCHAR>",
    "<SPACESEPCHAR1>",
    "<SPACESEPCHAR2>",
    "<SPACESEPCHAR3>",
    "<SPACESEPCHAR4>",
    "<SPACESEPCHAR5>",
    "<SPACESEPCHAR6>",
    "<SPACESEPCHAR7>",
    "<SPACESEPCHAR8>",
    "<SPACESEPCHAR9>",
    "<NGRAMTOKEN>",
    "<NONSPACESEPCHAR>",
    "<PUNCTUATION>",
    "<PUNCTCHAR1>",
    "<PUNCTCHAR2>",
    "<SPECIAL>",
  };

}
