/* Generated By:JJTree: Do not edit this line. LuceneASTfield.java */

package com.sun.labs.minion.retrieval.parser;

public class LuceneASTfield extends SimpleNode {
  public LuceneASTfield(int id) {
    super(id);
  }

  public LuceneASTfield(LuceneParser p, int id) {
    super(p, id);
  }

}
