/* Generated By:JJTree: Do not edit this line. LuceneASTAND.java */

package com.sun.labs.minion.retrieval.parser;

public class LuceneASTAND extends SimpleNode {
  public LuceneASTAND(int id) {
    super(id);
  }

  public LuceneASTAND(LuceneParser p, int id) {
    super(p, id);
  }

}
