/* Generated By:JJTree: Do not edit this line. LuceneASTq.java */

package com.sun.labs.minion.retrieval.parser;

public class LuceneASTq extends SimpleNode {
  public LuceneASTq(int id) {
    super(id);
  }

  public LuceneASTq(LuceneParser p, int id) {
    super(p, id);
  }

}
