/* Generated By:JJTree: Do not edit this line. LuceneASTUND.java */

package com.sun.labs.minion.retrieval.parser;

public class LuceneASTUND extends SimpleNode {
  public LuceneASTUND(int id) {
    super(id);
  }

  public LuceneASTUND(LuceneParser p, int id) {
    super(p, id);
  }

}
