/* Generated By:JJTree: Do not edit this line. /tank/work/Projects/minion/trunk/minion/src/com/sun/labs/minion/retrieval/parser/LuceneParserTreeConstants.java */

package com.sun.labs.minion.retrieval.parser;

public interface LuceneParserTreeConstants
{
  public int JJTDOPARSE = 0;
  public int JJTQ = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTUND = 4;
  public int JJTTERM = 5;
  public int JJTGROUP = 6;
  public int JJTFIELD = 7;
  public int JJTRANGE = 8;


  public String[] jjtNodeName = {
    "doParse",
    "q",
    "AND",
    "OR",
    "UND",
    "term",
    "group",
    "field",
    "range",
  };
}
