/* Generated By:JJTree: Do not edit this line. StrictASTfieldname.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTfieldname extends SimpleNode {
  public StrictASTfieldname(int id) {
    super(id);
  }

  public StrictASTfieldname(StrictParser p, int id) {
    super(p, id);
  }

}
