/* Generated By:JJTree: Do not edit this line. StrictASTindexed_fieldoperator.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTindexed_fieldoperator extends SimpleNode {
  public StrictASTindexed_fieldoperator(int id) {
    super(id);
  }

  public StrictASTindexed_fieldoperator(StrictParser p, int id) {
    super(p, id);
  }

}
