/* Generated By:JJTree: Do not edit this line. StrictASTsaved_fieldoperator.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTsaved_fieldoperator extends SimpleNode {
  public StrictASTsaved_fieldoperator(int id) {
    super(id);
  }

  public StrictASTsaved_fieldoperator(StrictParser p, int id) {
    super(p, id);
  }

}
