/* Generated By:JJTree: Do not edit this line. StrictASTq.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTq extends SimpleNode {
  public StrictASTq(int id) {
    super(id);
  }

  public StrictASTq(StrictParser p, int id) {
    super(p, id);
  }

}
