/* Generated By:JJTree: Do not edit this line. StrictASTqp.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTqp extends SimpleNode {
  public StrictASTqp(int id) {
    super(id);
  }

  public StrictASTqp(StrictParser p, int id) {
    super(p, id);
  }

}
