/* Generated By:JJTree: Do not edit this line. StrictASTdoParse.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTdoParse extends SimpleNode {
  public StrictASTdoParse(int id) {
    super(id);
  }

  public StrictASTdoParse(StrictParser p, int id) {
    super(p, id);
  }

}
