/* Generated By:JJTree: Do not edit this line. StrictASTqpOR.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTqpOR extends SimpleNode {
  public StrictASTqpOR(int id) {
    super(id);
  }

  public StrictASTqpOR(StrictParser p, int id) {
    super(p, id);
  }

}
