/* Generated By:JJTree: Do not edit this line. /Users/sg93990/Projects/new_minion/main/minion/src/com/sun/labs/minion/retrieval/parser/StrictParserTreeConstants.java */

package com.sun.labs.minion.retrieval.parser;

public interface StrictParserTreeConstants
{
  public int JJTDOPARSE = 0;
  public int JJTQ = 1;
  public int JJTQE = 2;
  public int JJTQP = 3;
  public int JJTQIAND = 4;
  public int JJTQPAND = 5;
  public int JJTQIOR = 6;
  public int JJTQPOR = 7;
  public int JJTQUND = 8;
  public int JJTQPPASS = 9;
  public int JJTTERM = 10;
  public int JJTQEPAREN = 11;
  public int JJTQIF = 12;
  public int JJTFIELDNAME = 13;
  public int JJTINDEXED_FIELDOPERATOR = 14;
  public int JJTSAVED_FIELDOPERATOR = 15;
  public int JJTSAVED_FIELDVALUE = 16;


  public String[] jjtNodeName = {
    "doParse",
    "q",
    "qe",
    "qp",
    "qiAND",
    "qpAND",
    "qiOR",
    "qpOR",
    "qUND",
    "qpPASS",
    "term",
    "qeparen",
    "qif",
    "fieldname",
    "indexed_fieldoperator",
    "saved_fieldoperator",
    "saved_fieldvalue",
  };
}
