/* Generated By:JJTree&JavaCC: Do not edit this line. StrictParserTokenManager.java */
package com.sun.labs.minion.retrieval.parser;

public class StrictParserTokenManager implements StrictParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 160:
         return jjStopAtPos(0, 2);
      case 5760:
         return jjStopAtPos(0, 3);
      case 6158:
         return jjStopAtPos(0, 4);
      case 8192:
         return jjStopAtPos(0, 5);
      case 8193:
         return jjStopAtPos(0, 6);
      case 8194:
         return jjStopAtPos(0, 7);
      case 8195:
         return jjStopAtPos(0, 8);
      case 8196:
         return jjStopAtPos(0, 9);
      case 8197:
         return jjStopAtPos(0, 10);
      case 8198:
         return jjStopAtPos(0, 11);
      case 8199:
         return jjStopAtPos(0, 12);
      case 8200:
         return jjStopAtPos(0, 13);
      case 8201:
         return jjStopAtPos(0, 14);
      case 8202:
         return jjStopAtPos(0, 15);
      case 8203:
         return jjStopAtPos(0, 16);
      case 8232:
         return jjStopAtPos(0, 17);
      case 8233:
         return jjStopAtPos(0, 18);
      case 8239:
         return jjStopAtPos(0, 19);
      case 8287:
         return jjStopAtPos(0, 20);
      case 12288:
         return jjStopAtPos(0, 21);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffe000000025040L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x3600000000ffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec3 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec4 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L
};
static final long[] jjbitVec5 = {
   0x0L, 0x0L, 0xffffffff00000000L, 0xffffffffffffffffL
};
static final long[] jjbitVec6 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec7 = {
   0x0L, 0xffffffffffff0000L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec8 = {
   0xffffffffffffffffL, 0xffff00000000ffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec9 = {
   0x0L, 0xffffffff00000000L, 0xffffffffffffffffL, 0xffffffffL
};
static final long[] jjbitVec10 = {
   0x200002L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec11 = {
   0x0L, 0x0L, 0x420040000000000L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec12 = {
   0x7fffffffffffffL, 0xffffffffffff0000L, 0xffffffffffffffffL, 0x401f0003ffc3L
};
static final long[] jjbitVec13 = {
   0x0L, 0x400000000000000L, 0xfffffffbffffd740L, 0xfbfffffffff7fffL
};
static final long[] jjbitVec14 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffffffc03L, 0x33fffffffff7fffL
};
static final long[] jjbitVec15 = {
   0xfffe00000000ffffL, 0xfffffffe027fffffL, 0xffL, 0x707ffffff0000L
};
static final long[] jjbitVec16 = {
   0xfffffffd0000L, 0xe000L, 0x2003fffffffffL, 0x0L
};
static final long[] jjbitVec17 = {
   0x23fffffffffffff0L, 0xffc3ff010000L, 0x23c5fdfffff99fe0L, 0x3ffc3b0000000L
};
static final long[] jjbitVec18 = {
   0x36dfdfffff987e0L, 0x1cffc05e000000L, 0x23edfdfffffbbfe0L, 0xffc300010000L
};
static final long[] jjbitVec19 = {
   0x23edfdfffff99fe0L, 0x2ffc3b0000000L, 0x0L, 0x0L
};
static final long[] jjbitVec20 = {
   0x0L, 0x0L, 0x2ffbfffffc7fffe0L, 0x7fL
};
static final long[] jjbitVec21 = {
   0x6fbffffffffL, 0x3f03ffL, 0x0L, 0x0L
};
static final long[] jjbitVec22 = {
   0xffffffffffffff7fL, 0xffffffff3d7f3d7fL, 0x7f3d7fffffff3d7fL, 0xffff7fffff7f7f3dL
};
static final long[] jjbitVec23 = {
   0xffffffff7f3d7fffL, 0x3fe0007ffff7fL, 0xffffffff00000000L, 0x1fffffffffffffL
};
static final long[] jjbitVec24 = {
   0xffffffffffffffffL, 0x7f9fffffffffffL, 0xffffffff07fffffeL, 0x7ffffffffffL
};
static final long[] jjbitVec25 = {
   0x3ffff0003dfffL, 0x1dfff0003ffffL, 0xfffffffffffffL, 0x3ff10800000L
};
static final long[] jjbitVec26 = {
   0xffffffff03ff0000L, 0xffffffffffffffL, 0x1ffffffffffL, 0x0L
};
static final long[] jjbitVec27 = {
   0x1fffffffL, 0x1f3fffffffffc0L, 0x0L, 0x0L
};
static final long[] jjbitVec28 = {
   0xffffffffffffffffL, 0xfffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec29 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffff0fffffffL, 0x3ffffffffffffffL
};
static final long[] jjbitVec30 = {
   0xffffffff3f3fffffL, 0x3fffffffaaff3f3fL, 0x5fdfffffffffffffL, 0x1fdc1fff0fcf1fdcL
};
static final long[] jjbitVec31 = {
   0x0L, 0x8002000000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec32 = {
   0xe3fbbd503e2ffc84L, 0x3e0L, 0x0L, 0x0L
};
static final long[] jjbitVec33 = {
   0x5f7ffdffa0f8007fL, 0xffdbL, 0x0L, 0x0L
};
static final long[] jjbitVec34 = {
   0x7fffffe03ff0000L, 0x7fffffeL, 0x0L, 0x0L
};
static final long[] jjbitVec35 = {
   0x0L, 0x0L, 0x8880080200000000L, 0x0L
};
static final long[] jjbitVec36 = {
   0x0L, 0x4000000000000000L, 0x80L, 0x0L
};
static final long[] jjbitVec37 = {
   0x0L, 0xfc000000L, 0x4000000000000600L, 0x18000000000009L
};
static final long[] jjbitVec38 = {
   0x88003000L, 0x3c0000000000L, 0x0L, 0x100000L
};
static final long[] jjbitVec39 = {
   0x3fffL, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec40 = {
   0x0L, 0x1003000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec41 = {
   0x0L, 0x0L, 0x0L, 0x10000000000000L
};
static final long[] jjbitVec42 = {
   0x0L, 0xc008000L, 0x0L, 0x0L
};
static final long[] jjbitVec43 = {
   0x3c0000000007fff0L, 0x0L, 0x20L, 0x0L
};
static final long[] jjbitVec44 = {
   0x0L, 0xfc00L, 0x0L, 0x800000000000000L
};
static final long[] jjbitVec45 = {
   0x0L, 0x1fe00000000L, 0x0L, 0x0L
};
static final long[] jjbitVec46 = {
   0x0L, 0x600000000000L, 0x18000000L, 0x380000000000L
};
static final long[] jjbitVec47 = {
   0x60000000000000L, 0x0L, 0x0L, 0x7700000L
};
static final long[] jjbitVec48 = {
   0x7ffL, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec49 = {
   0x0L, 0x30L, 0x0L, 0x0L
};
static final long[] jjbitVec50 = {
   0xffff00ffffff0000L, 0x60000000009bffefL, 0x6000L, 0x0L
};
static final long[] jjbitVec51 = {
   0x60000000000L, 0x0L, 0x70000000000000L, 0x0L
};
static final long[] jjbitVec52 = {
   0x0L, 0x3fff0000000000L, 0x0L, 0xfc000000000L
};
static final long[] jjbitVec53 = {
   0x0L, 0x0L, 0x1fffff8L, 0x300000000f000000L
};
static final long[] jjbitVec54 = {
   0x20010000fff3ff0eL, 0x0L, 0x100000000L, 0x800000000000000L
};
static final long[] jjbitVec55 = {
   0xc000000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec56 = {
   0xffff000000000000L, 0xd0bfff7ffffL, 0x0L, 0x0L
};
static final long[] jjbitVec57 = {
   0xb80000018c00f7eeL, 0x3fa8000000L, 0x0L, 0x0L
};
static final long[] jjbitVec58 = {
   0x0L, 0x0L, 0x100000000L, 0x0L
};
static final long[] jjbitVec59 = {
   0x0L, 0x0L, 0x1L, 0x0L
};
static final long[] jjbitVec60 = {
   0x4000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec61 = {
   0x830000000fffL, 0x80000000L, 0x0L, 0x0L
};
static final long[] jjbitVec62 = {
   0x1L, 0x0L, 0x0L, 0x0L
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 484;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0xdc00fc7a00000000L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(0, 3);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(4, 8);
                  }
                  else if (curChar == 39)
                  {
                     if (kind > 68)
                        kind = 68;
                     jjCheckNAddStates(9, 14);
                  }
                  else if (curChar == 34)
                  {
                     if (kind > 67)
                        kind = 67;
                     jjCheckNAddStates(15, 20);
                  }
                  else if (curChar == 41)
                  {
                     if (kind > 63)
                        kind = 63;
                  }
                  else if (curChar == 40)
                  {
                     if (kind > 62)
                        kind = 62;
                  }
                  else if (curChar == 61)
                  {
                     if (kind > 57)
                        kind = 57;
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 69)
                        kind = 69;
                     jjCheckNAddStates(21, 23);
                  }
                  else if (curChar == 60)
                     jjAddStates(24, 100);
                  else if (curChar == 46)
                     jjCheckNAdd(10);
                  else if (curChar == 62)
                  {
                     if (kind > 65)
                        kind = 65;
                  }
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if (curChar == 60)
                  {
                     if (kind > 64)
                        kind = 64;
                  }
                  else if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 0:
                  if (curChar == 61 && kind > 56)
                     kind = 56;
                  break;
               case 2:
                  if (curChar == 61 && kind > 57)
                     kind = 57;
                  break;
               case 3:
                  if (curChar == 61 && kind > 61)
                     kind = 61;
                  break;
               case 4:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 40 && kind > 62)
                     kind = 62;
                  break;
               case 6:
                  if (curChar == 41 && kind > 63)
                     kind = 63;
                  break;
               case 7:
                  if (curChar == 60 && kind > 64)
                     kind = 64;
                  break;
               case 8:
                  if (curChar == 62 && kind > 65)
                     kind = 65;
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjCheckNAdd(10);
                  break;
               case 13:
                  if (curChar != 39)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 16:
                  if ((0xdc00fc7a00000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 19:
                  if (curChar != 40)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 20:
                  if (curChar != 41)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 21:
                  if (curChar != 61)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 22:
                  if (curChar != 34)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(15, 20);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(15, 20);
                  break;
               case 25:
                  if ((0xdc00fffa00000000L & l) != 0L)
                     jjCheckNAddStates(15, 20);
                  break;
               case 26:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddStates(15, 20);
                  break;
               case 27:
                  if (curChar == 34 && kind > 71)
                     kind = 71;
                  break;
               case 29:
                  if (curChar == 34)
                     jjCheckNAddStates(15, 20);
                  break;
               case 30:
                  if (curChar == 39)
                     jjCheckNAddStates(15, 20);
                  break;
               case 32:
                  if (curChar == 40)
                     jjCheckNAddStates(15, 20);
                  break;
               case 33:
                  if (curChar == 41)
                     jjCheckNAddStates(15, 20);
                  break;
               case 34:
                  if (curChar == 61)
                     jjCheckNAddStates(15, 20);
                  break;
               case 35:
                  if (curChar != 39)
                     break;
                  if (kind > 68)
                     kind = 68;
                  jjCheckNAddStates(9, 14);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(9, 14);
                  break;
               case 38:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddStates(9, 14);
                  break;
               case 39:
                  if ((0xdc00ff7a00000000L & l) != 0L)
                     jjCheckNAddStates(9, 14);
                  break;
               case 40:
                  if (curChar == 39 && kind > 71)
                     kind = 71;
                  break;
               case 42:
                  if (curChar == 39)
                     jjCheckNAddStates(9, 14);
                  break;
               case 44:
                  if (curChar == 34)
                     jjCheckNAddStates(9, 14);
                  break;
               case 45:
                  if (curChar == 40)
                     jjCheckNAddStates(9, 14);
                  break;
               case 46:
                  if (curChar == 41)
                     jjCheckNAddStates(9, 14);
                  break;
               case 47:
                  if (curChar == 61)
                     jjCheckNAddStates(9, 14);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(21, 23);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAdd(49);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(50, 9);
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(4, 8);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(54);
                  break;
               case 55:
                  if (curChar == 60)
                     jjAddStates(24, 100);
                  break;
               case 56:
                  if (curChar == 62 && kind > 25)
                     kind = 25;
                  break;
               case 63:
                  if (curChar == 62 && kind > 26)
                     kind = 26;
                  break;
               case 72:
                  if (curChar == 62 && kind > 27)
                     kind = 27;
                  break;
               case 77:
                  if (curChar == 62 && kind > 28)
                     kind = 28;
                  break;
               case 84:
                  if (curChar == 62 && kind > 29)
                     kind = 29;
                  break;
               case 96:
                  if (curChar == 62 && kind > 30)
                     kind = 30;
                  break;
               case 100:
                  if (curChar == 62 && kind > 31)
                     kind = 31;
                  break;
               case 113:
                  if (curChar == 62 && kind > 32)
                     kind = 32;
                  break;
               case 124:
                  if (curChar == 62 && kind > 33)
                     kind = 33;
                  break;
               case 133:
                  if (curChar == 62 && kind > 34)
                     kind = 34;
                  break;
               case 142:
                  if (curChar == 62 && kind > 35)
                     kind = 35;
                  break;
               case 153:
                  if (curChar == 62 && kind > 36)
                     kind = 36;
                  break;
               case 162:
                  if (curChar == 62 && kind > 37)
                     kind = 37;
                  break;
               case 171:
                  if (curChar == 62 && kind > 38)
                     kind = 38;
                  break;
               case 180:
                  if (curChar == 62 && kind > 39)
                     kind = 39;
                  break;
               case 193:
                  if (curChar == 62 && kind > 40)
                     kind = 40;
                  break;
               case 206:
                  if (curChar == 62 && kind > 41)
                     kind = 41;
                  break;
               case 215:
                  if (curChar == 62 && kind > 42)
                     kind = 42;
                  break;
               case 230:
                  if (curChar == 62 && kind > 43)
                     kind = 43;
                  break;
               case 249:
                  if (curChar == 62 && kind > 44)
                     kind = 44;
                  break;
               case 264:
                  if (curChar == 62 && kind > 45)
                     kind = 45;
                  break;
               case 279:
                  if (curChar == 62 && kind > 46)
                     kind = 46;
                  break;
               case 290:
                  if (curChar == 62 && kind > 47)
                     kind = 47;
                  break;
               case 307:
                  if (curChar == 62 && kind > 48)
                     kind = 48;
                  break;
               case 312:
                  if (curChar == 62 && kind > 49)
                     kind = 49;
                  break;
               case 329:
                  if (curChar == 62 && kind > 50)
                     kind = 50;
                  break;
               case 338:
                  if (curChar == 47)
                     jjCheckNAdd(339);
                  break;
               case 339:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(339, 340);
                  break;
               case 340:
                  if (curChar == 62 && kind > 51)
                     kind = 51;
                  break;
               case 345:
                  if (curChar == 47)
                     jjCheckNAdd(346);
                  break;
               case 346:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(346, 340);
                  break;
               case 351:
                  if (curChar == 62 && kind > 52)
                     kind = 52;
                  break;
               case 364:
                  if (curChar == 62 && kind > 53)
                     kind = 53;
                  break;
               case 371:
                  if (curChar == 62 && kind > 54)
                     kind = 54;
                  break;
               case 400:
                  if (curChar == 62 && kind > 55)
                     kind = 55;
                  break;
               case 413:
                  if (curChar == 62 && kind > 56)
                     kind = 56;
                  break;
               case 419:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 418;
                  break;
               case 428:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 427;
                  break;
               case 432:
                  if (curChar == 62 && kind > 57)
                     kind = 57;
                  break;
               case 445:
                  if (curChar == 62 && kind > 58)
                     kind = 58;
                  break;
               case 454:
                  if (curChar == 62 && kind > 59)
                     kind = 59;
                  break;
               case 469:
                  if (curChar == 62 && kind > 60)
                     kind = 60;
                  break;
               case 476:
                  if (curChar == 61 && kind > 60)
                     kind = 60;
                  break;
               case 477:
                  if (curChar == 62 && kind > 61)
                     kind = 61;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(4, 8);
                  }
                  else if ((0x78000001a8000001L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(0, 3);
                  }
                  else if (curChar == 92)
                  {
                     if (kind > 66)
                        kind = 66;
                     jjCheckNAddStates(101, 105);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 72)
                        kind = 72;
                  }
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L && kind > 72)
                     kind = 72;
                  break;
               case 12:
                  if (curChar != 92)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAddStates(101, 105);
                  break;
               case 15:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 16:
                  if ((0x78000001a8000001L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 17:
                  if (curChar == 92)
                     jjCheckNAddStates(101, 105);
                  break;
               case 18:
                  if (curChar != 92)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 24:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(15, 20);
                  break;
               case 25:
                  if ((0x78000001a8000001L & l) != 0L)
                     jjCheckNAddStates(15, 20);
                  break;
               case 28:
                  if (curChar == 92)
                     jjAddStates(106, 111);
                  break;
               case 31:
                  if (curChar == 92)
                     jjCheckNAddStates(15, 20);
                  break;
               case 37:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(9, 14);
                  break;
               case 39:
                  if ((0x78000001a8000001L & l) != 0L)
                     jjCheckNAddStates(9, 14);
                  break;
               case 41:
                  if (curChar == 92)
                     jjAddStates(112, 117);
                  break;
               case 43:
                  if (curChar == 92)
                     jjCheckNAddStates(9, 14);
                  break;
               case 53:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(4, 8);
                  break;
               case 54:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(54);
                  break;
               case 57:
                  if (curChar == 68)
                     jjCheckNAdd(56);
                  break;
               case 58:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 100)
                     jjCheckNAdd(56);
                  break;
               case 61:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 64:
                  if (curChar == 68)
                     jjCheckNAdd(63);
                  break;
               case 65:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 100)
                     jjCheckNAdd(63);
                  break;
               case 69:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 73:
                  if (curChar == 82)
                     jjCheckNAdd(72);
                  break;
               case 74:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 114)
                     jjCheckNAdd(72);
                  break;
               case 76:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 78:
                  if (curChar == 82)
                     jjCheckNAdd(77);
                  break;
               case 79:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 114)
                     jjCheckNAdd(77);
                  break;
               case 82:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 85:
                  if (curChar == 68)
                     jjCheckNAdd(84);
                  break;
               case 86:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 100)
                     jjCheckNAdd(84);
                  break;
               case 90:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 82 && kind > 30)
                     kind = 30;
                  break;
               case 94:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 97:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 101:
                  if (curChar == 69)
                     jjCheckNAdd(100);
                  break;
               case 102:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 101)
                     jjCheckNAdd(100);
                  break;
               case 108:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 114:
                  if (curChar == 84)
                     jjCheckNAdd(113);
                  break;
               case 115:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 116)
                     jjCheckNAdd(113);
                  break;
               case 120:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 125:
                  if (curChar == 69)
                     jjCheckNAdd(124);
                  break;
               case 126:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 101)
                     jjCheckNAdd(124);
                  break;
               case 130:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 134:
                  if (curChar == 69)
                     jjCheckNAdd(133);
                  break;
               case 135:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 101)
                     jjCheckNAdd(133);
                  break;
               case 139:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 143:
                  if (curChar == 72)
                     jjCheckNAdd(142);
                  break;
               case 144:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 104)
                     jjCheckNAdd(142);
                  break;
               case 149:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 154:
                  if (curChar == 68)
                     jjCheckNAdd(153);
                  break;
               case 155:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 100)
                     jjCheckNAdd(153);
                  break;
               case 159:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 163:
                  if (curChar == 77)
                     jjCheckNAdd(162);
                  break;
               case 164:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 109)
                     jjCheckNAdd(162);
                  break;
               case 168:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 172:
                  if (curChar == 68)
                     jjCheckNAdd(171);
                  break;
               case 173:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 100)
                     jjCheckNAdd(171);
                  break;
               case 177:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 181:
                  if (curChar == 68)
                     jjCheckNAdd(180);
                  break;
               case 182:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 100)
                     jjCheckNAdd(180);
                  break;
               case 188:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 194:
                  if (curChar == 83)
                     jjCheckNAdd(193);
                  break;
               case 195:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if (curChar == 115)
                     jjCheckNAdd(193);
                  break;
               case 201:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 207:
                  if (curChar == 83)
                     jjCheckNAdd(206);
                  break;
               case 208:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 115)
                     jjCheckNAdd(206);
                  break;
               case 212:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 213:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 216:
                  if (curChar == 83)
                     jjCheckNAdd(215);
                  break;
               case 217:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 115)
                     jjCheckNAdd(215);
                  break;
               case 224:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 231:
                  if (curChar == 71)
                     jjCheckNAdd(230);
                  break;
               case 232:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 103)
                     jjCheckNAdd(230);
                  break;
               case 241:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 250:
                  if (curChar == 82)
                     jjCheckNAdd(249);
                  break;
               case 251:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 114)
                     jjCheckNAdd(249);
                  break;
               case 258:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 263:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 265:
                  if (curChar == 69)
                     jjCheckNAdd(264);
                  break;
               case 266:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 101)
                     jjCheckNAdd(264);
                  break;
               case 273:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 274:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 275:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 276:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 280:
                  if (curChar == 83)
                     jjCheckNAdd(279);
                  break;
               case 281:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 284:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 115)
                     jjCheckNAdd(279);
                  break;
               case 286:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 287:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 289:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 291:
                  if (curChar == 69)
                     jjCheckNAdd(290);
                  break;
               case 292:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 293:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 294:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 295:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 296:
                  if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 297:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 298:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 299:
                  if (curChar == 101)
                     jjCheckNAdd(290);
                  break;
               case 300:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 301:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 302:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 303:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 304:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 306:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 308:
                  if (curChar == 70)
                     jjCheckNAdd(307);
                  break;
               case 309:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 310:
                  if (curChar == 102)
                     jjCheckNAdd(307);
                  break;
               case 311:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 313:
                  if (curChar == 83)
                     jjCheckNAdd(312);
                  break;
               case 314:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 313;
                  break;
               case 315:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 314;
                  break;
               case 316:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 315;
                  break;
               case 317:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 318:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 317;
                  break;
               case 319:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 318;
                  break;
               case 320:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 321:
                  if (curChar == 115)
                     jjCheckNAdd(312);
                  break;
               case 322:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 323:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 324:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 325:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 324;
                  break;
               case 326:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 325;
                  break;
               case 327:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 328:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 327;
                  break;
               case 330:
                  if (curChar == 82)
                     jjCheckNAdd(329);
                  break;
               case 331:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 330;
                  break;
               case 332:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 333:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 334:
                  if (curChar == 114)
                     jjCheckNAdd(329);
                  break;
               case 335:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 336:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 337:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 341:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 342:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 341;
                  break;
               case 343:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 344:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 343;
                  break;
               case 347:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 345;
                  break;
               case 348:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 349:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 348;
                  break;
               case 350:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 349;
                  break;
               case 352:
                  if (curChar == 84)
                     jjCheckNAdd(351);
                  break;
               case 353:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 352;
                  break;
               case 354:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 353;
                  break;
               case 355:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 354;
                  break;
               case 356:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 355;
                  break;
               case 357:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 356;
                  break;
               case 358:
                  if (curChar == 116)
                     jjCheckNAdd(351);
                  break;
               case 359:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 358;
                  break;
               case 360:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 359;
                  break;
               case 361:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 360;
                  break;
               case 362:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 361;
                  break;
               case 363:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 362;
                  break;
               case 365:
                  if (curChar == 84)
                     jjCheckNAdd(364);
                  break;
               case 366:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 365;
                  break;
               case 367:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 366;
                  break;
               case 368:
                  if (curChar == 116)
                     jjCheckNAdd(364);
                  break;
               case 369:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 368;
                  break;
               case 370:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 369;
                  break;
               case 372:
                  if (curChar == 68)
                     jjCheckNAdd(371);
                  break;
               case 373:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 372;
                  break;
               case 374:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 373;
                  break;
               case 375:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 374;
                  break;
               case 376:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 375;
                  break;
               case 377:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 376;
                  break;
               case 378:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 377;
                  break;
               case 379:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 378;
                  break;
               case 380:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 379;
                  break;
               case 381:
                  if (curChar == 100)
                     jjCheckNAdd(371);
                  break;
               case 382:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 381;
                  break;
               case 383:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 382;
                  break;
               case 384:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 383;
                  break;
               case 385:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 384;
                  break;
               case 386:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 385;
                  break;
               case 387:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 386;
                  break;
               case 388:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 387;
                  break;
               case 389:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 388;
                  break;
               case 390:
                  if (curChar == 70)
                     jjCheckNAdd(371);
                  break;
               case 391:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 390;
                  break;
               case 392:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 391;
                  break;
               case 393:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 392;
                  break;
               case 394:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 393;
                  break;
               case 395:
                  if (curChar == 102)
                     jjCheckNAdd(371);
                  break;
               case 396:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 395;
                  break;
               case 397:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 396;
                  break;
               case 398:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 397;
                  break;
               case 399:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 398;
                  break;
               case 401:
                  if (curChar == 78)
                     jjCheckNAdd(400);
                  break;
               case 402:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 401;
                  break;
               case 403:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 402;
                  break;
               case 404:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 403;
                  break;
               case 405:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 404;
                  break;
               case 406:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 405;
                  break;
               case 407:
                  if (curChar == 110)
                     jjCheckNAdd(400);
                  break;
               case 408:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 407;
                  break;
               case 409:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 408;
                  break;
               case 410:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 409;
                  break;
               case 411:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 410;
                  break;
               case 412:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 411;
                  break;
               case 414:
                  if (curChar == 76)
                     jjCheckNAdd(413);
                  break;
               case 415:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 414;
                  break;
               case 416:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 415;
                  break;
               case 417:
                  if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 416;
                  break;
               case 418:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 417;
                  break;
               case 420:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 419;
                  break;
               case 421:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 420;
                  break;
               case 422:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 421;
                  break;
               case 423:
                  if (curChar == 108)
                     jjCheckNAdd(413);
                  break;
               case 424:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 423;
                  break;
               case 425:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 424;
                  break;
               case 426:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 425;
                  break;
               case 427:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 426;
                  break;
               case 429:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 428;
                  break;
               case 430:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 429;
                  break;
               case 431:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 430;
                  break;
               case 433:
                  if (curChar == 83)
                     jjCheckNAdd(432);
                  break;
               case 434:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 433;
                  break;
               case 435:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 434;
                  break;
               case 436:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 435;
                  break;
               case 437:
                  if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 436;
                  break;
               case 438:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 437;
                  break;
               case 439:
                  if (curChar == 115)
                     jjCheckNAdd(432);
                  break;
               case 440:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 439;
                  break;
               case 441:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 440;
                  break;
               case 442:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 441;
                  break;
               case 443:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 442;
                  break;
               case 444:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 443;
                  break;
               case 446:
                  if (curChar == 83)
                     jjCheckNAdd(445);
                  break;
               case 447:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 446;
                  break;
               case 448:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 447;
                  break;
               case 449:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 448;
                  break;
               case 450:
                  if (curChar == 115)
                     jjCheckNAdd(445);
                  break;
               case 451:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 450;
                  break;
               case 452:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 451;
                  break;
               case 453:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 452;
                  break;
               case 455:
                  if (curChar == 82)
                     jjCheckNAdd(454);
                  break;
               case 456:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 455;
                  break;
               case 457:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 456;
                  break;
               case 458:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 457;
                  break;
               case 459:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 458;
                  break;
               case 460:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 459;
                  break;
               case 461:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 460;
                  break;
               case 462:
                  if (curChar == 114)
                     jjCheckNAdd(454);
                  break;
               case 463:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 462;
                  break;
               case 464:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 463;
                  break;
               case 465:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 464;
                  break;
               case 466:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 465;
                  break;
               case 467:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 466;
                  break;
               case 468:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 467;
                  break;
               case 470:
                  if (curChar == 81)
                     jjCheckNAdd(469);
                  break;
               case 471:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 470;
                  break;
               case 472:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 471;
                  break;
               case 473:
                  if (curChar == 113)
                     jjCheckNAdd(469);
                  break;
               case 474:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 473;
                  break;
               case 475:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 474;
                  break;
               case 478:
                  if (curChar == 81)
                     jjCheckNAdd(477);
                  break;
               case 479:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 478;
                  break;
               case 480:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 479;
                  break;
               case 481:
                  if (curChar == 113)
                     jjCheckNAdd(477);
                  break;
               case 482:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 481;
                  break;
               case 483:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 482;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(118, 122);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(4, 8);
                  }
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAddStates(0, 3);
                  }
                  break;
               case 14:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(123, 126);
                  break;
               case 15:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 16:
                  if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(0, 3);
                  break;
               case 23:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(127, 132);
                  break;
               case 24:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(15, 20);
                  break;
               case 25:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(15, 20);
                  break;
               case 26:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(15, 20);
                  break;
               case 36:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(133, 138);
                  break;
               case 37:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(9, 14);
                  break;
               case 38:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(9, 14);
                  break;
               case 39:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(9, 14);
                  break;
               case 51:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(118, 122);
                  break;
               case 52:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAdd(52);
                  break;
               case 53:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(4, 8);
                  break;
               case 54:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(54);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 484 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   14, 15, 16, 17, 14, 15, 16, 54, 17, 36, 37, 38, 39, 40, 41, 23, 
   24, 25, 26, 27, 28, 49, 50, 9, 59, 62, 67, 71, 74, 76, 80, 83, 
   88, 92, 95, 99, 106, 112, 118, 123, 128, 132, 137, 141, 147, 152, 157, 161, 
   166, 170, 175, 179, 186, 192, 199, 205, 210, 214, 222, 229, 239, 248, 256, 263, 
   271, 278, 284, 289, 298, 306, 309, 311, 320, 328, 333, 337, 344, 350, 357, 363, 
   367, 370, 380, 389, 394, 399, 406, 412, 422, 431, 438, 444, 449, 453, 461, 468, 
   472, 475, 476, 480, 483, 13, 18, 19, 20, 21, 29, 30, 31, 32, 33, 34, 
   42, 43, 44, 45, 46, 47, 15, 16, 52, 17, 14, 15, 16, 17, 14, 24, 
   25, 26, 27, 28, 23, 37, 38, 39, 40, 41, 36, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 11:
         return ((jjbitVec2[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec3[i2] & l2) != 0L);
      case 15:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec8[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec9[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec11[i2] & l2) != 0L);
      case 2:
         return ((jjbitVec12[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec13[i2] & l2) != 0L);
      case 4:
         return ((jjbitVec14[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec15[i2] & l2) != 0L);
      case 7:
         return ((jjbitVec16[i2] & l2) != 0L);
      case 9:
         return ((jjbitVec17[i2] & l2) != 0L);
      case 10:
         return ((jjbitVec18[i2] & l2) != 0L);
      case 11:
         return ((jjbitVec19[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec20[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec21[i2] & l2) != 0L);
      case 18:
         return ((jjbitVec22[i2] & l2) != 0L);
      case 19:
         return ((jjbitVec23[i2] & l2) != 0L);
      case 20:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec24[i2] & l2) != 0L);
      case 23:
         return ((jjbitVec25[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec26[i2] & l2) != 0L);
      case 25:
         return ((jjbitVec27[i2] & l2) != 0L);
      case 29:
         return ((jjbitVec28[i2] & l2) != 0L);
      case 30:
         return ((jjbitVec29[i2] & l2) != 0L);
      case 31:
         return ((jjbitVec30[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec31[i2] & l2) != 0L);
      case 33:
         return ((jjbitVec32[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec33[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec34[i2] & l2) != 0L);
      default : 
         if ((jjbitVec10[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec35[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec36[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec37[i2] & l2) != 0L);
      case 6:
         return ((jjbitVec38[i2] & l2) != 0L);
      case 7:
         return ((jjbitVec39[i2] & l2) != 0L);
      case 9:
         return ((jjbitVec40[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec41[i2] & l2) != 0L);
      case 14:
         return ((jjbitVec42[i2] & l2) != 0L);
      case 15:
         return ((jjbitVec43[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec44[i2] & l2) != 0L);
      case 19:
         return ((jjbitVec45[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec46[i2] & l2) != 0L);
      case 23:
         return ((jjbitVec47[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec48[i2] & l2) != 0L);
      case 25:
         return ((jjbitVec49[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec50[i2] & l2) != 0L);
      case 35:
         return ((jjbitVec51[i2] & l2) != 0L);
      case 39:
         return ((jjbitVec52[i2] & l2) != 0L);
      case 41:
         return ((jjbitVec53[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec54[i2] & l2) != 0L);
      case 253:
         return ((jjbitVec55[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec56[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec57[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec58[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec59[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec60[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec61[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec62[i2] & l2) != 0L);
      default : 
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xfffffffffe000001L, 0x28033ffL, 
};
static final long[] jjtoSkip = {
   0x1fffffeL, 0x0L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[484];
private final int[] jjstateSet = new int[968];
protected char curChar;
public StrictParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public StrictParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 484; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
