/* Generated By:JJTree: Do not edit this line. StrictASTsaved_fieldvalue.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTsaved_fieldvalue extends SimpleNode {
  public StrictASTsaved_fieldvalue(int id) {
    super(id);
  }

  public StrictASTsaved_fieldvalue(StrictParser p, int id) {
    super(p, id);
  }

}
