/* Generated By:JJTree: Do not edit this line. StrictASTqiOR.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTqiOR extends SimpleNode {
  public StrictASTqiOR(int id) {
    super(id);
  }

  public StrictASTqiOR(StrictParser p, int id) {
    super(p, id);
  }

}
