/* Generated By:JJTree: Do not edit this line. StrictASTqpAND.java */

package com.sun.labs.minion.retrieval.parser;

public class StrictASTqpAND extends SimpleNode {
  public StrictASTqpAND(int id) {
    super(id);
  }

  public StrictASTqpAND(StrictParser p, int id) {
    super(p, id);
  }

}
