/* Generated By:JJTree: Do not edit this line. WebASTq.java */

package com.sun.labs.minion.retrieval.parser;

public class WebASTq extends SimpleNode {
  public WebASTq(int id) {
    super(id);
  }

  public WebASTq(WebParser p, int id) {
    super(p, id);
  }

}
