/* Generated By:JJTree: Do not edit this line. WebASTterm.java */

package com.sun.labs.minion.retrieval.parser;

public class WebASTterm extends SimpleNode {
  public WebASTterm(int id) {
    super(id);
  }

  public WebASTterm(WebParser p, int id) {
    super(p, id);
  }

}
