/* Generated By:JJTree: Do not edit this line. WebASTpassageTerm.java */

package com.sun.labs.minion.retrieval.parser;

public class WebASTpassageTerm extends SimpleNode {
  public WebASTpassageTerm(int id) {
    super(id);
  }

  public WebASTpassageTerm(WebParser p, int id) {
    super(p, id);
  }

}
