/* Generated By:JJTree: Do not edit this line. WebASTdoParse.java */

package com.sun.labs.minion.retrieval.parser;

public class WebASTdoParse extends SimpleNode {
  public WebASTdoParse(int id) {
    super(id);
  }

  public WebASTdoParse(WebParser p, int id) {
    super(p, id);
  }

}
