/* Generated By:JJTree&JavaCC: Do not edit this line. WebParserConstants.java */
package com.sun.labs.minion.retrieval.parser;

public interface WebParserConstants {

  int EOF = 0;
  int PLUS = 25;
  int MINUS = 26;
  int FSLASH = 27;
  int TILDE = 28;
  int DUBQUOTE = 29;
  int LB = 30;
  int RB = 31;
  int VALIDCHAR = 32;
  int PHRASE = 33;
  int PASSAGE = 34;
  int TERM = 35;
  int WHITESPACE = 36;
  int WHITECHAR = 37;
  int SPACESEPTOKEN = 38;
  int SPACESEPCHAR = 39;
  int SPACESEPCHAR1 = 40;
  int SPACESEPCHAR2 = 41;
  int SPACESEPCHAR3 = 42;
  int SPACESEPCHAR4 = 43;
  int SPACESEPCHAR5 = 44;
  int SPACESEPCHAR6 = 45;
  int SPACESEPCHAR7 = 46;
  int SPACESEPCHAR8 = 47;
  int SPACESEPCHAR9 = 48;
  int NGRAMTOKEN = 49;
  int NONSPACESEPCHAR = 50;
  int PUNCTUATION = 51;
  int PUNCTCHAR1 = 52;
  int PUNCTCHAR2 = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\u1680\"",
    "\"\\u180e\"",
    "\"\\u2000\"",
    "\"\\u2001\"",
    "\"\\u2002\"",
    "\"\\u2003\"",
    "\"\\u2004\"",
    "\"\\u2005\"",
    "\"\\u2006\"",
    "\"\\u2007\"",
    "\"\\u2008\"",
    "\"\\u2009\"",
    "\"\\u200a\"",
    "\"\\u200b\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "\"\\u202f\"",
    "\"\\u205f\"",
    "\"\\u3000\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"~\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "<VALIDCHAR>",
    "<PHRASE>",
    "<PASSAGE>",
    "<TERM>",
    "<WHITESPACE>",
    "<WHITECHAR>",
    "<SPACESEPTOKEN>",
    "<SPACESEPCHAR>",
    "<SPACESEPCHAR1>",
    "<SPACESEPCHAR2>",
    "<SPACESEPCHAR3>",
    "<SPACESEPCHAR4>",
    "<SPACESEPCHAR5>",
    "<SPACESEPCHAR6>",
    "<SPACESEPCHAR7>",
    "<SPACESEPCHAR8>",
    "<SPACESEPCHAR9>",
    "<NGRAMTOKEN>",
    "<NONSPACESEPCHAR>",
    "<PUNCTUATION>",
    "<PUNCTCHAR1>",
    "<PUNCTCHAR2>",
  };

}
