/* Generated By:JavaCC: Do not edit this line. JCCTokenizerConstants.java */
package com.sun.labs.minion.document.tokenizer;

public interface JCCTokenizerConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int WHITECHAR = 2;
  int SPACESEPTOKEN = 3;
  int SPACESEPCHAR = 4;
  int SPACESEPCHAR1 = 5;
  int SPACESEPCHAR2 = 6;
  int SPACESEPCHAR3 = 7;
  int SPACESEPCHAR4 = 8;
  int SPACESEPCHAR5 = 9;
  int SPACESEPCHAR6 = 10;
  int SPACESEPCHAR7 = 11;
  int SPACESEPCHAR8 = 12;
  int SPACESEPCHAR9 = 13;
  int NGRAMTOKEN = 14;
  int NONSPACESEPCHAR = 15;
  int PUNCTUATION = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<WHITECHAR>",
    "<SPACESEPTOKEN>",
    "<SPACESEPCHAR>",
    "<SPACESEPCHAR1>",
    "<SPACESEPCHAR2>",
    "<SPACESEPCHAR3>",
    "<SPACESEPCHAR4>",
    "<SPACESEPCHAR5>",
    "<SPACESEPCHAR6>",
    "<SPACESEPCHAR7>",
    "<SPACESEPCHAR8>",
    "<SPACESEPCHAR9>",
    "<NGRAMTOKEN>",
    "<NONSPACESEPCHAR>",
    "<PUNCTUATION>",
  };

}
